CC = ntox86-gcc
STRIP = ntox86-strip
PYROOT = $(QNX_TARGET)/x86/
EXTRA_CFLAGS = -I$(QNX_TARGET)/usr/include/python3.2m

PYTGT = ../_alf_grammar.ntox86.so

SOURCES = alf_grammar.c \
	  wchoice.c \
	  gen_state.c \
	  grammar.c \
	  rnd.c \
	  symbol.c

HEADERS = alf_grammar.h \
	  wchoice.h \
	  gen_state.h \
	  grammar.h \
	  rnd.h \
	  symbol.h

CFLAGS= -g -O3 -Wall -Wshadow -fPIC -fno-builtin \
	  $(EXTRA_CFLAGS)

all: $(PYTGT)

clean:
	rm -f $(PYTGT)

$(PYTGT): Makefile.ntox86 $(SOURCES) $(HEADERS)
	$(CC) -shared -Wl,-soname,$@ -Wl,-z,notext $(CFLAGS) \
		-o $@ $(SOURCES) \
		-L$(PYROOT)/usr/lib \
		-lpython3.2m
	$(STRIP) --strip-unneeded $@

.PHONY: all clean

